diskfs/go-diskfs

partition/gpt/table.go, partition/gpt/table_test.go
Fixes #10 
Two issues:
1. Test for gpt `GetPartitionSize()` was comparing sizes of partitions that have no size at all, so 0*anything still was 0, and test passed, even though it should have failed. Test now checks first partition, which has proper size.
2. gpt `GetPartitionSize()` was multiplying partition size by sector size, even though size already was in bytes.
=> Fix test for GetPartitionSize, and fix GetPartitionSize for GPT

filesystem/iso9660/finalize.go
When calculating the 8.3 filename we replace all characters
that are not [A-Z0-9_] with _
Signed-off-by: Darren Shepherd <darren@rancher.com>
=> Replace illegal characters in shortname with _

disk/disk.go, disk/disk_test.go, filesystem/fat32/fat32.go, filesystem/fat32/fat32_test.go, partition/mbr/partiton.go
I needed labels for a project I'm working on. They are recognized by Linux, so everything should be good from that perspective. This specific implementation adds a Disk#CreateFilesystemSpecial that takes a structure with parameters... with the assumption that additional details can just be added to the structure without having to then change signatures all around.
Sorry, the MBR write came along with the PR... I had committed and pushed before I realized I needed a branch!
=> filesystem labels

partition/mbr/partition_internal_test.go, partition/mbr/partiton.go, partition/mbr/table_test.go
MBR partition writeContents() was not checking against the number of bytes in the partition when checking size. Replicated logic from readContents() and updated unit tests.
Review carefully please as I needed to change more in the unit tests than I would have expected.
=> Allowing MBR writeContents() to write successfully

filesystem/iso9660/iso9660.go, filesystem/iso9660/iso9660_test.go
The original iso9660 implementation allowed block sizes of 512, 1024, 2048, etc. However, only exponents of 2048 are allowed: 2048, 4096, 8192, etc. This corrects it and fixes the tests
=> Only allow valid iso9660 block sizes

disk/disk.go, disk/disk_test.go, diskfs.go, diskfs_test.go
Here I propose a new function to open a disk device with a user selected mode: the OpenWithMode() function.
With this function, clients are able to execute read-only operations in situations where the device is already open for write. For instance, LVM physical volumes will already be open for write and then this library does not support this case which is a very common case these days.
Clients can also make use of the library in a safer mode when just reading the current disk partitioning format is required and then make sure no change to the disk will be allowed.
The proposed changes adds a new flag to the Disk structure to indicate it is writable or not. This flag is used to explicitly fail any operation which would modify the disk if it was opened in read-only mode.
The original …
=> introduce OpenWithMode()

diskfs.go
Please consider this fix for a misleading error message in the OpenWithMode() function.
Now it correctly prints the selected file open mode and also wraps the lower level error.
Signed-off-by: Guilherme Magalhaes <guilherme.magalhaes@hpe.com>
=> fix error message in OpenWithMode()

filesystem/fat32/fat32.go
Fixes #48 
Problem was that the number of sectors in a fat32 is a uint32 (max 4GB), so the parameter blocks used a uint32 for the data start offset, which we use to calculate where inside the partition to write things.
When the partition is inside a disk (block device or image), you need to add the offset from, the disk start. Since the whole disk can be much larger than the max of a uint32; go's `WriteAt/ReadAt` take an int64.
When doing the calculation, you need to convert from the uint32 to the int64, while doing calculations en route. The initial math (reasons lost to the mists of time) converted parameters to a uint32 (matching the `dataStart` parameter) to do the math, then up to `int64` to do the `WriteAt()`. 
The correct thing (provided by this PR) is to upconvert everything to an …
=> Handle disks larger than 4 GB

disk/disk.go, disk/disk_test.go
Fixes #52 
`FileInfo.Size()` works correctly when the disk is a disk image. However, when it is an actual block device, it returns 0. This is _precisely_ why we have [this code](https://github.com/diskfs/go-diskfs/blob/3bd1f70075f0eed12a5e50c1c38c39b94c755bd6/diskfs.go#L192-L205), to calculate it for a block device. We then forget to take advantage of the saved size as `Disk.Size`. 
This uses the correct sizing.
=> fix block device sizing

disk/disk.go, disk/disk_unix.go, disk/disk_windows.go
force kernel to reread partition table after successfully writing a partition table to the disk. This is done by an ioctl call with BLKRRPART request
Fixes : #56 
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>
=> force kernel to reread partition table

disk/disk_unix.go
because BLKRRPART is not available on all platforms.
=> fix missing unix symbol

partition/mbr/types.go
From https://en.wikipedia.org/wiki/Partition_type#PID_EEh
```
0xEE GPT protective MBR
0xEF EFI system partition
```
=> Fix GPTProtective partition type (0xee) for hybrid/protective MBRs

disk/disk_test.go, partition/gpt/partiton.go
The Partition.Size attribute of the gpt packages is already in bytes.
Use GetSize() and GetStart() to avoid byte/sector confusion.
=> Fix GPT partition reading

filesystem/fat32/dos71bpb.go, filesystem/fat32/dos71bpb_internal_test.go, filesystem/fat32/fat32.go, filesystem/fat32/fat32_internal_test.go
Fixes fsck.vfat complais about the backup blocks:
- boot sector is copied to the backup block location
- filesystem information is packed into the next logical block
- fat backup is written alongside the primary copy
fsck.vfat does not complain about these issues after applying the patch
=> Correctly write backup blocks

filesystem/fat32/fat32.go
Allocate space will link the old chain with the new chain. This can only
work if previous is pointing to the last cluster of the privious chain.
=> Fix allocateSpace if previous points to the beginning of a chain

filesystem/fat32/fat32_test.go, filesystem/fat32/file.go
This PR (based on #64 ) fixes streaming fat32 file writes.
After each write the file offset should be advanced by the number of bytes written. see commit dd19876
=> Fix streaming fat32 file write

filesystem/fat32/fat32.go, filesystem/fat32/fat32_test.go
While trying to generate an RPI boot image I noticed that the library fails to create a root directory with all files.
After adding a failing test case (woohoo) I discovered that the `allocateSpace` function needs to be called with a file size and the beginning of the current chain (otherwise the size delta is not computable).
Also wiring up the chain was problematic.
After applying these changes the 32 file root directory test passes.
EDIT: there is also a drive-by commit: minClusterSize and maxClusterSize were swapped :see_no_evil:
=> Fix root folder clusters

filesystem/fat32/fat32.go
The cluster location of parent directory entries (`..`) pointing to the root directory (`/`) must be 0, not 2. `fsck.vfat` complains about this.
Currently based on #64 for testing purposes (large root folder)
=> Fix cluster location of .. directory entry

README.md
This fixes a typo on the README with the import statement
=> Fixed typo in readme import

diskfs.go, diskfs_unix.go, diskfs_windows.go
This doesn't get block devices working on Windows, but it allows everything else to work, which is a step forward.
We need to figure out how to read/write block devices directly on Windows.
Fixes #75
=> separate windows and unix for block devices

filesystem/iso9660/common_internal_test.go, filesystem/iso9660/file.go, filesystem/iso9660/file_test.go
`size` here is the amount we have left to write. To determine if we
are done, we need to compare the new offset to the total size of
the file.
Without this fix we would always bail at around halfway
(+/- the buffer size) through any file larger than the buffer size.
=> Finish reading the entire file in iso9660

filesystem/iso9660/finalize.go, filesystem/iso9660/finalize_test.go
Previously this directory which contained all the files in the iso
would be left in the temp directory.
Fixes #90
=> Remove the iso workspace after running Finalize

examples/iso_info.go, filesystem/iso9660/file.go
Fixes #92
With this I can get the basic info I would get from `isoinfo` which is the size and location.
Here's an example program:
```go
package main
import (
"fmt"
"os"
"path/filepath"
"github.com/diskfs/go-diskfs"
"github.com/diskfs/go-diskfs/filesystem"
"github.com/diskfs/go-diskfs/filesystem/iso9660"
)
func main() {
disk, err := diskfs.Open("test.iso")
if err != nil {
fmt.Println(err)
return
}
fs, err := disk.GetFilesystem(0)
if err != nil {
fmt.Println(err)
return
}
err = fileInfoFor("/", fs)
if err != nil {
fmt.Printf("Failed to get file infos: %s\n", err)
}
}
func fileInfoFor(path string, fs filesystem.FileSystem) error {
files, err := fs.ReadDir(path)
if err != nil {
return err
}
for _, file := range files {
fullPath := filepath.Join(path, file.Name())
if file.IsDir() {
err = …
```
=> Add iso file Location() function

disk/disk.go, filesystem/iso9660/finalize_test.go, filesystem/iso9660/iso9660.go, filesystem/iso9660/iso9660_test.go
This will allow for users to either create an iso from files in an
existing directory or just to specify a directory to be used as the
scratch space for staging files.
If nothing is provided we will fallback to the previous behavior
which would create a directory in the system temp directory
Fixes #100
=> Allow providing a workspace in iso9660.Create

filesystem/fat32/testdata/fat32.go
The change to refactor `CreateFilesystem` broke the ` testdata/fat32.go` helper. This change fixes it.
=> Fix fat32.go test image generator

filesystem/fat32/file.go
=> fix reading of partial clusters in fat32

filesystem/fat32/directoryentry.go, filesystem/fat32/directoryentry_internal_test.go, filesystem/fat32/doc.go
fixes #113 
Previosuly, we only had A-Z,0-9,~ as valid shortname characters. Rereading the spec, clearly there are about 10 more.
=> use full set of valid characters for fat32 short name

filesystem/fat32/fat32.go, filesystem/fat32/fat32_test.go, filesystem/fat32/file.go, filesystem/fat32/table.go, filesystem/file.go, filesystem/iso9660/file.go, filesystem/squashfs/file.go, filesystem/squashfs/file_internal_test.go
Also fixes #115 
It doesn't add O_TRUNC support to the other filesystems, but those can come later
=> include Closer for all filesystem files; fix O_TRUNC in fat32

disk/disk.go
Previously, it is only possible to read a partition after
writing the partition table.
Now, a call to GetPartitionTable will enable calls to GetPartition
and GetFilesystem to succeed without having to write a new partition
table.
=> disk: When GetPartitionTable succeeds, save result

Makefile
We were doing `go get`, which really doesn't work and isn't how they recommend to install it.
=> install golangci-lint sanely and officially

Makefile, disk/disk_unix.go, filesystem/squashfs/compressor.go, util/version.go
Remove final dependency on deprecated golint, replace with revive. Update to pass linting.
=> update golint to revive, fix linting issues

filesystem/iso9660/finalize.go
If there is an error getting the file information at any point in the
tree info will be nil and err will be set. The WalkFunc must decide how
to handle the passed error.
In this case, as we can't finalize the iso, we choose to error out.
Before this fix, a failure to access some file in the tree would cause a
panic.
=> Check the filepath.WalkFunc error in iso9660.Finalize

filesystem/fat32/file.go
Fix for untrapped errors raised by FAT32 disk (mentioned in https://github.com/diskfs/go-diskfs/issues/130).
=> trap FAT32 disk WriteAt errors

README.md, diskfs.go, diskfs_test.go, examples/bootable_iso.go, examples/efi_create.go, examples/iso_create.go, examples/squashfs_create.go, filesystem/fat32/testdata/fat32.go
This fixes #133 .
As discussed on the issue above, per recommendation I added an additional parameter to the `diskfs.Create()` function that allows customization of sector size - currently only in the case of regular files.
Questions here:
1. Should we also override the sector size for block devices in this case? I wasn't sure so I left it to auto-detect always.
2. Naming. It's hard for me to find good names for the values!
Please be gentle, Go is still not very native for me.
=> Add the ability to adjust the sector size while creating Disks

diskfs.go, diskfs_test.go
Reduces the proliferation of options to `Open()`, and eliminates the need for additional functions like `OpenWithMode()`.
=> variadic options for diskfs.Open

diskfs.go, diskfs_darwin.go, diskfs_unix.go, go.mod, go.sum
- Adds support for disk blocks on darwin (`/dev/(r)?disk.+`)
- Updated the /sys/unix dependency and based the `ioctl` syscalls from its constants instead in linux
Notes:
- It still works with regular files on darwin, happens that the previous ioctl syscall flags are specific for some unix systems (linux included), but not for freebsd and darwin.
=> Add Darwin disk blocks support (/dev/diskX / /dev/rdiskX)

filesystem/iso9660/finalize.go
findEntry does not understand what to do when path.Dir returns "." on a file with no directory. This happens when we don't pass a BootCatalog, the default ones do not contain a path, or when we include a BootFile without any path.
Signed-off-by: Morten Linderud <morten.linderud@mullvad.net>
=> iso9660/finalize: parse empty path correctly

partition/mbr/types.go
Value is from
https://tldp.org/HOWTO/Partition-Mass-Storage-Definitions-Naming-HOWTO/x190.html https://en.wikipedia.org/wiki/Partition_type
Signed-off-by: Leslie Qi Wang <qiwa@pensando.io>
=> add linux swap partition type

partition/gpt/table.go
In some cases this slice is ends up out of bounds so check capacity before indexing to prevent a panic.
Specifically this happens with the Fedora 37 Server iso here: https://download.fedoraproject.org/pub/fedora/linux/releases/37/Server/x86_64/iso/Fedora-Server-dvd-x86_64-37-1.7.iso
Just trying to `diskfs.Open("Fedora-Server-dvd-x86_64-37-1.7.iso")` causes the following panic:
```
panic: runtime error: slice bounds out of range [:32768] with capacity 17408
goroutine 1 [running]:
github.com/diskfs/go-diskfs/partition/gpt.tableFromBytes({0xc00013a000, 0xc00013a000?, 0x4400}, 0x200, 0x4864af?)
/home/ncarboni/Source/go-diskfs/partition/gpt/table.go:376 +0xc57
github.com/diskfs/go-diskfs/partition/gpt.Read({0x589128, 0xc000014038}, 0x200, 0x50?) …
```
=> partition/gpt: check partitions array size before indexing

diskfs.go
Some errors returned by the Create function were too generic. 
Here is an example of a previous error output : 
`could not create device my-disk.iso`
Now it's as follows : 
`could not create device my-disk.iso: The file exists.`
I changed the return statements in order to add the unwrapped original syscall error.
=> Improved error handling for Create()

diskfs.go
Looks like if its a block device, on initDisk we re-open the block device to get the size, but unfortunately we never close it. As the life of that os.File is very short, we should release it as soon as possible in case other process may be trying to access the same block device
Signed-off-by: Itxaka <itxaka@spectrocloud.com>
=> Close file on InitDisk if its a block device

.github/workflows/ci.yaml, diskfs.go, diskfs_darwin.go, diskfs_linux.go, diskfs_other.go, diskfs_windows.go
Currently, diskfs attempts to detect the size of a block device using a
"seek" based approach. Unfortunately, while this looks generic, it does
not work on Mac, at least not in a VM.
Based on the previous commit, this commit adds a Mac and Linux
implementation for getting the size of a Block device through IOCTL
inspired by https://github.com/tytso/e2fsprogs/blob/master/lib/ext2fs/getsize.c
This was manually tested using a Linux loopback device and in a Mac
virtual machine.
=> Detect block device size using platform-specific IOCTL on Mac & Linux

diskfs.go
Add RDWR mode for `diskfs.Open(...)`, so partitions could be resized without exclusive write access. For example **growpart** uses **sgdisk** to resize partitions on running systems.
=> add rdrw open disk mode

filesystem/fat32/directoryentry.go, go.mod, go.sum
Proposing use of `ASCIISet` instead of `map[byte]bool`.
`ASCIISet` is a zero-dependency library for sets of ASCII characters with [28 times faster lookup speed](https://github.com/elliotwutingfeng/asciiset#results) than `map[byte]bool`.
=> Use ASCIISet

filesystem/iso9660/directoryentry.go
Hi, this commit adds basic symlink support for iso9660 filesystems with Rockridge extension.
(Far from perfect but allows to handle symlinks manually at least)
=> iso9660: add basic symlink support

diskfs_test.go, partition/gpt/table.go, partition/mbr/table.go, partition/table.go
Based on #112, and addressing review comments. Thanks to the original author! @thebsdbox
1. add Repair and Verify interfaces in type table
2. add test to test opening the GPT image
=> partition: add repair capabilities to GPT

filesystem/squashfs/directory.go
This was causing "corrupted directory, had 257 entries instead of max
256" errors, however this was because parseDirectoryHeader had already
added one to the count.
=> squashfs: fix off by one in directory counting

filesystem/squashfs/squashfs.go
Using mksquashfs 1:4.5-3build1 and these flags causes the created
squash file not have xattrs but this is indicated by the index being
all 1s rather than the flag in the superblock.
mksquashfs $IMG $IMG.sqfs -comp zstd -Xcompression-level 3 -b 1M -no-xattrs -all-root
=> squashfs: sometimes missing xattrs seems to be marked with 0xffffffffffffffff

partition/gpt/partition.go, partition/gpt/table.go, partition/mbr/partition.go, partition/mbr/table.go, partition/mbr/table_internal_test.go, partition/part/partition.go, partition/table.go
This allows to retrieve the partition table UUID and partition UUID for MBR formatted disks. The partition table UUID (aka "disk identifier" or "disk signature") can be used to identify a disk when using the MBR format scheme. The partition UUID is then just the partition table UUID with the partitions index number appended.
=> MBR: add partition table UUID and partition UUID

filesystem/squashfs/file.go
Before this change, we would spend an awful lot of CPU time reading
and decompressing the same block to only read a small part from it.
This change caches the last block used in the file handle and for
typical block sizes used in reads this makes a 10x difference in
throughput.
=> squashfs: cache the last block decompressed in the file for 10x speedup

filesystem/squashfs/const_internal_test.go, filesystem/squashfs/directoryentry.go, filesystem/squashfs/directoryentry_internal_test.go, filesystem/squashfs/squashfs.go, filesystem/squashfs/squashfs_test.go
This implements a way to read the target of symlinks as discussed in #200 
It is divided into two parts, the first a bit of refactoring, then the second the implementation of the new method.
- squashfs: move UID(),GID(),Xattr() methods to directory entry #200
- squashfs: implement Readlink() method on directory entry
=> squashfs: implement a way to read the target of symlinks

filesystem/squashfs/const_internal_test.go, filesystem/squashfs/directoryentry.go, filesystem/squashfs/squashfs.go, filesystem/squashfs/squashfs_test.go
This enables us to open the file directly from the directory listing which saves doing another directory traversal to find it again.
This uses a simple `Open` method modeled on the one in the zip archive [File.Open](https://pkg.go.dev/archive/zip#File.Open)
When extracting all the entries from the archive this makes a significant performance improvement as re-reading all the directory entries from the root is quite expensive.
=> squashfs: factor read only OpenFile into Open method on directory entry

filesystem/squashfs/lru.go, filesystem/squashfs/lru_test.go, filesystem/squashfs/metadatablock.go, filesystem/squashfs/metadatablock_internal_test.go, filesystem/squashfs/squashfs.go, filesystem/squashfs/squashfs_test.go
This adds a configurable block cache as discussed in #205
This is done in 3 commits for ease of review - it compiles and the tests pass at each commit so they can be merged as 3 commits if desired.
With this cache this now performs within a factor of 2 of unsquashfs
- squashfs: make readMetadata a method on FileSystem
- squashfs: add LRU cache for blocks
- squashfs: use the LRU cache for fragments and metadata
=> squashfs: add configurable block cache

filesystem/iso9660/eltorito.go, filesystem/iso9660/finalize.go
Please, see discussion at https://github.com/diskfs/go-diskfs/issues/210
=> Fix for truncated boot image size recorded with ElTorito boot catalog and boot info table.

filesystem/fat32/fat32.go
Please, see discussion at https://github.com/diskfs/go-diskfs/issues/212
=> Provide proper create/modify/access timestamps for special FAT-32 directory entries ("." and "..").

filesystem/iso9660/directoryentrysystemuseextension.go, filesystem/iso9660/finalize.go, filesystem/iso9660/iso9660.go, filesystem/iso9660/rockridge.go, filesystem/iso9660/rockridge_internal_test.go
The rock ridge extensions at various places assumed all files were actual files in the workspace. However, `finalizeFileInfo` supports in-memory files.
The solution is to extend `finalizeFileInfo` to have the additional features rock ridge is looking for: accessTime, modTime, linkTarget. `finalizeFileInfo` already implements `fs.FileInfo`. Then we can convert the call to RockRidge to just accept `finalizeFileInfo` and get the properties.
My tests show it works.
Fixes #215
=> iso9660 finalizeFileInfo contain enough info for rockridge extensions

partition/gpt/table.go, partition/gpt/table_test.go
The last usable data sector should be the sector of the start of the backup partition table - 1, but it does not subtract the 1. This fixes it and adds an additional test with sgdisk to verify.
=> Fix off-by-one error in GPT last data sector

filesystem/ext4/ext4.go
Fixes #231 
For ext4, reading the group descriptor table (GDT), it was assuming that the GDT always followed right after the superblock, which is right after the padding bytes. This is true when blocksize is 1024, as padding = block 0, superblock = block 1, GDT = block 2. However, if it is larger than 1024, then padding + superblock = block 0, GDT = block 1.
=> read GDT table from correct block

filesystem/ext4/common_test.go, filesystem/ext4/ext4.go, filesystem/ext4/superblock.go, go.mod, go.sum
github.com/google/uuid was already a dependency so I removed the github.com/satori/go.uuid dependency that was introduced recently 
satori/go.uuid looks to be no longer maintained as of 2018
=> Removed go.uuid dependency

partition/gpt/partition.go, partition/gpt/table.go, partition/gpt/table_test.go
These changes allow:
* observing the total size and last data sector of a GPT
* resizing a GPT (for example to make it fit its block device)
* expanding a GPT partition
=> Allow resizing a GPT

README.md
The example inlined in the README seems to be for an older version of the package. Let's not try to maintain it, pointing at the example file instead.
=> doc: remove outdated example in README, point to real source instead

filesystem/ext4/common_test.go, filesystem/ext4/testdata/buildimg.sh
The tests were using `dumpe2fs`/`debugfs -R "stats"` (same thing) to get information about the superblock to use for tests. Mostly that works, except for lifetime writes. That is rounded to MB, which makes it difficult to get the correct number, and sometimes is wrong, which makes the 2 bytes in the calculation incorrect, and makes the checksum wrong.
This instead reads the specific bytes from the superblock via `dd` and uses that as the accurate number.
=> get more accurate read of ext4 superblock in tests

diskfs.go
Fixes https://github.com/diskfs/go-diskfs/issues/237
=> Wrap errors, not Unwrap

filesystem/iso9660/finalize.go, filesystem/squashfs/finalize.go
Fixes #244 
The iso finalization originally was written without parallelism in mind. Most of it works fine. The inly issue was walking the workspace to finalize. Because it is easier to work with relative paths, it did a `os.Chdir(workspace)` followed by a `filepath.Walk(".",...)`. In most cases, this works fine, but if you run in parallel, different threads start changing the current directory and mess up things like creating files or removing files or walking trees.
In general, `os.Chdir()` is not a friendly thing to do in libraries, so it is good to remove it.
Both iso9660 and squashfs did this, so fixed in both places.
Thanks to @mchuang3 for the excellent issue in #244, with a simple recreation.
=> iso9660 and squashfs support for parallel writings

filesystem/ext4/ext4.go
Two ext4 fixes in this:
* correctly calculate minimum size when 0 provided for defaults
* correctly calculate max filesystem size for 64-bit and 32-bit. Somehow, it was using bitwise math instead of exponents. I suspect it was a shorthand I wrote and then forgot.
=> create ext4 with correct sizes

partition/gpt/table.go
Currently both tables point to the primary GPT partition entry array which doesn't make a lot of sense. Pass "primary" to t.partitionArraySector() to get the right address for each of the tables instead.
I found this because I was building images for a Chrombook and noticed that [cgpt](https://packages.ubuntu.com/oracular/cgpt) always reported the secondary GPT header as corrupted. 
For comparison here is the `cgpt show` output without this fix for a minimal ESP example:
```
start        size    part  contents
0           1          PMBR
1           1          Pri GPT header
Sig: [EFI PART]
Rev: 0x00010000
Size: 92 (blocks)
Header CRC: 0x56d22730 
My LBA: 1
Alternate LBA: 212991
First LBA: 34
Last LBA: 212958
Disk UUID: F4206CB2-52F5-4BEA-B903-62A6CC3DDAFB
Entries LBA: 2
Number of …
```
=> gpt: point alternate PartitionEntryLBA to alternate GPT table

filesystem/fat32/fat32.go, filesystem/fat32/fat32_test.go
=> fix fat32 case-insensitivity when creating files, add test for it

filesystem/fat32/directoryentry.go, filesystem/fat32/fat32.go, filesystem/fat32/fat32_test.go, filesystem/fat32/testdata/mkfat32.sh
Let me know if any changes are required.
I wasn't sure if adding another 10MB fat32 image built with mtools was the best way to go for the unit tests but was a little confused when I tried to add it to the existing fat32.img file, it seems that file is not built by the shell script in the same folder.
=> Closes #250: fat32 8.3 lowercase names, make fs.OpenFile case insensitive for 8.3 and long filenames

filesystem/fat32/common_test.go, filesystem/fat32/fat32.go, filesystem/fat32/fat32_internal_test.go, filesystem/fat32/table.go, filesystem/fat32/table_internal_test.go
Hello,
We're looking to use go-diskfs to build an air-gapped installer image for our product. It includes a bunch of files (like grub tree), OCI images, binaries and etc. 
The speed up is 20+ times on bigger file systems - from 540 seconds to 23 seconds for a 1G image with two partitions of ~500MB each.
The test setup is:
```
Intel(R) Core(TM) Ultra 7 155H, 32GiB RAM, SN740 NVMe WD 512GB
go 1.23.0
6.10.7-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC
```
Here are three profiling reports:
- Unmodified: [v1.4.1.pdf](https://github.com/user-attachments/files/16949444/v1.4.1.pdf)
- Removing keys sort: [v1.4.1-nosort.pdf](https://github.com/user-attachments/files/16949443/v1.4.1-nosort.pdf)
- Replacing map with slice: [v1.4.1-nomap.pdf](https://github.com/user-attachments/files/16949442/v1.4.1-nomap.pd …
=> Speed up fat32 impl

filesystem/fat32/fat32_test.go, filesystem/fat32/file.go
Fixes the issue raised by @mrbojangles3. 
With thanks to @mrbojangles3, whose tests are now incorporated into `fat32_test.go`
=> fix offset when reading and writing fat32 files to avoid overruns

filesystem/fat32/fat32_test.go, go.mod
Go 1.22 has not reached its EOL yet
=> go.mod: restore Go 1.22 support

disk/disk.go, filesystem/ext4/ext4.go, filesystem/fat32/fat32.go, filesystem/fat32/fat32_test.go, filesystem/fat32/file.go, filesystem/filesystem.go, filesystem/iso9660/file.go, filesystem/iso9660/iso9660.go, filesystem/squashfs/file.go, filesystem/squashfs/squashfs.go
Interface is extended as a part of ext4 improvements effort
https://github.com/diskfs/go-diskfs/issues/9#issuecomment-2422384742
Also, Remove method is introduced for all supported filesystems.
@deitch should we keep `ext4.Rm()` or we can drop it alltogether infavour of newly introduced `filesystem.Remove()`?
=> Extend filesystem interface

.devcontainer/devcontainer.json, .gitignore, .vscode/extensions.json, .vscode/settings.json
@deitch tooling is factored out into this PR.
Comments are welcome!
=> Add VS Code tooling

.devcontainer/devcontainer.json
As some fat32 tests need docker, devcontainer needs a tweak for that
Followup for https://github.com/diskfs/go-diskfs/pull/266
=> Add docker-in-docker for devcontainer

filesystem/fat32/file.go
For some low-level filesystem operations it can be beneficial to both get the cluster chain of a given file as well as querying where exactly on disk the file contents reside.
Examples where such info might be useful:
- Perform secure erase
- Detect file fragmentation
- Pass Disk byte offset or LBA to a different tool that can work with it
This PR adds two functions, one to just expose the internal getClustersList via the File type.
The other to express the same info directly in disk areas, where each area is described by its starting byte and a length in bytes. (further conversion to disk sectors / LBA can be easily performed by the caller.)
=> FAT32: add functions to get File cluster chain and disk areas

filesystem/squashfs/const_internal_test.go, filesystem/squashfs/inode_internal_test.go, filesystem/squashfs/squashfs.go, filesystem/squashfs/squashfs_internal_test.go, filesystem/squashfs/xattr.go, filesystem/squashfs/xattr_internal_test.go
fixes: diskfs/go-diskfs/issues/276
=> fix: xattr table index to split position into decompressed and compressed offset

filesystem/squashfs/inode.go, filesystem/squashfs/inode_internal_test.go, filesystem/squashfs/squashfs.go
Got an error when trying to read another squashfs file from ubuntu. Not sure if I should have created an issue first. It was raising [this](https://github.com/diskfs/go-diskfs/blob/master/filesystem/squashfs/xattr.go#L23) error. Traced it down to a symlink reading the wrong part for the xattr.
=> fix: dont include xattr in extended link reading

filesystem/iso9660/finalize_test.go, filesystem/iso9660/iso9660.go
prior this fix if TMPDIR is set to something like `/tmp//` the iso9660 creation would cause panic.
now it's fixed + test case is added according to @dietch review
=> Fix panic when tmp path is inccurate

filesystem/squashfs/finalize.go
Due to SquashFS spec
https://dr-emann.github.io/squashfs/squashfs.html#_directory_inodes Section 5.2, it says about directory inode file size
'''
This value is 3 bytes larger than the real listing. The Linux
kernel creates "." and ".." entries for offsets 0 and 1, and only after 3 looks into the listing, subtracting 3 from the size. '''
In go-disks the size is calculated by serialize the 'directory'. A directory serialization includes multiple 'directoryHeader's and 'directoryEntryRaw's. This aligns with the dir_size calculation logic with well-known squasjfs-tools project
https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/mksquashfs.c#L1549
Note that the file_size is set to 3 larger than the size.
Thus here, we set directoryLocation.size to 3 bytes larger and the new …
=> squashfs: fix directory inode size

filesystem/squashfs/const_internal_test.go, filesystem/squashfs/file.go, filesystem/squashfs/finalize.go, filesystem/squashfs/inode.go, filesystem/squashfs/inode_internal_test.go
https://dr-emann.github.io/squashfs/squashfs.html#_file_inodes
Due to SquashFS spec, file inode's 'blocks start' field means the offset from the beginning of the file.
This commit also fixes the fragmentData location calculation.
Finally, due to Spec, if a file does not have fragment data, its frag index should be all 0xF.
Fixes #282
=> Squashfs: fix error format when file larger than block size

filesystem/squashfs/squashfs_test.go
should incorporate fix as well. Initial test fails, until fix gets in.
=> test for squashfs writing and reading errors

filesystem/iso9660/iso9660.go, filesystem/iso9660/volume_descriptor.go
SVDs may have version greater than 1. For now let's check PVD version only.
closes https://github.com/diskfs/go-diskfs/issues/290
=> Support ISO version 2 reading

filesystem/iso9660/finalize.go
=> fix iso9660 write error when writing directories

filesystem/fat32/directoryentry.go, filesystem/fat32/file.go
Added the ability to set and check file attributes for the FAT32 file system, including system files, hidden files, and read-only files. These attributes are correctly encoded and decoded in directory entries to ensure persistence and consistency of file attributes.
=> feat(fat32): Add file system attribute setting and checking functions

.gitignore, filesystem/squashfs/compressor.go, filesystem/squashfs/compressor_internal_test.go, go.mod, go.sum
This adds support for LZO decompression (not compression) capabilities for squashfs filesystems. The underlying library is MIT licensed and supports LZO1X only (which is fairly common).
=> Add LZO decompressor

filesystem/squashfs/const_internal_test.go, filesystem/squashfs/file.go, filesystem/squashfs/file_test.go
Fix: #299
Cache the previous block size too, so when deciding to use the cached block can compare size to handle sparse blocks
=> fix: handle caching sparse reading block
