diskfs/go-diskfs

- filesystem/fat32/fat32.go
- filesystem/fat32/testdata/README.md
- filesystem/fat32/testdata/fat32.go
- filesystem/fat32/testdata/mkfat32.sh
This caused subdirectories not to be viewed properly.
> Fix issue with missing directory entries for . and ..

- filesystem/iso9660/finalize.go
> Enable custom ISO volume identifier

- README.md
- diskfs.go
> Correctly open for read-write

- filesystem/iso9660/rockridge.go
- filesystem/iso9660/statt_others.go
- filesystem/iso9660/statt_windows.go
Not sure this is the actual fix but my windows compiles are solid now with this change locally. If you want changes ask and I'll fix.
> Split Stat_t for windows

- README.md
- examples/efi_create.go
- examples/filesystem_read.go
> add examples

- examples/iso_create.go
Fixes #37 
Do you mind that I based the example on your code @kstieger? Please comment here.
> Add iso example

- filesystem/fat32/fat32.go
> Ensure root directory is zeroed out

- filesystem/fat32/directory.go
- filesystem/fat32/directoryentry.go
- filesystem/fat32/fat32.go
> fix volume label for fat32

- .github/workflows/ci.yaml
- disk/disk.go
- disk/disk_test.go
- filesystem/fat32/fat32.go
- filesystem/fat32/fat32_test.go
- go.mod
- go.sum
- partition/gpt/partition_internal_test.go
- partition/gpt/partiton.go
- partition/gpt/table.go
- partition/gpt/table_internal_test.go
- partition/gpt/table_test.go
- partition/mbr/partition_internal_test.go
- partition/mbr/partiton.go
- partition/mbr/table.go
- partition/mbr/table_test.go
- partition/part/partition.go
- partition/table.go
This will give the ability to do more things with partitions.
> direct access to partition structures

- diskfs_unix.go
- diskfs_windows.go
- filesystem/iso9660/directoryentry_internal_test.go
- go.mod
- go.sum
> correctly handle unix/windows builds

- filesystem/iso9660/finalize.go
Partially fixes #80. There may be other issues preventing it, but this is necessary.
> calculate sizes for boot catalog correctly

- filesystem/iso9660/eltorito.go
Includes comment describing it
> option to pass loadsize to eltorito

- diskfs.go
Thanks to @xaduha for finding this
> fix err formatting

- filesystem/iso9660/directoryentry.go
- filesystem/iso9660/iso9660.go
> handle zero-length root directory size error

- diskfs.go
- diskfs_unix.go
Fixes #104 
@mraerino please try this branch and let us know if it works.
> correct fixed value for physical size ioctl

- partition/gpt/table.go
- partition/gpt/table_internal_test.go
Fixes #157 
When we read the GPT table, we read the bytes necessary for table including assumed partition entries, then try to parse them all.
This doesn't work, because our assumptions of the partition entries could very well be wrong.
This PR changes it to a few steps:
1. Read the bytes just for the GPT header
2. Parse and validate those
3. Using the data from the header, read the bytes for the partition entries
4. Validate the checksum on the bytes for the partition entries
5. Parse the partition entries and add to the table struct
> separate reading of GPT table and partition entries

- partition/gpt/partition.go
- partition/gpt/table.go
> ignore GPT partitions that are marked unused by UUID

- filesystem/iso9660/directoryentry.go
- filesystem/iso9660/iso9660_test.go
- filesystem/iso9660/testdata/iso-in-folder/abc
- filesystem/iso9660/testdata/iso-in-folder/subfolder1/hello.txt
- filesystem/iso9660/testdata/rock-ridge-in-folder/abc
- filesystem/iso9660/testdata/rock-ridge-in-folder/subfolder1/hello.txt
- filesystem/iso9660/testdata/rock-ridge-in-folder/this-is-a-file-with-a-very-long-filename-longer-than-30-chars
Fixed #189 
Also added basic tests
> iso rock ridge should handle creating with filenames longer than 30 chars

- disk/disk.go
> disk: add Disk.Close()

- partition/gpt/table.go
- partition/gpt/table_internal_test.go
This modifies the GPT table Repair method to update the last data sector and the Verify method to check for this. If this is not done, it can result in e.g. sgdisk warning of a partition overlapping the last data sector when the disk is resized.
A test has been added to create a disk with a GPT table and verify it, then resize and repair it and verify again successfully.
> GPT table repair should reset last data sector

- filesystem/fat32/fat32.go
> fix typo on fat32 tables error message

- filesystem/iso9660/finalize.go
- filesystem/iso9660/rockridge.go
> support serial in iso9660 rock ridge 1.12

- filesystem/fat32/fat32.go
- filesystem/fat32/fat32_test.go
Fixes https://github.com/diskfs/go-diskfs/issues/239
> Make fat32 ReadDir not return special volume label

- disk/disk.go
- examples/iso_create.go
- examples/squashfs_create.go
- filesystem/ext4/ext4.go
- filesystem/fat32/fat32.go
- filesystem/filesystem.go
- filesystem/iso9660/iso9660.go
- filesystem/squashfs/squashfs.go
Please  see the concrete commit messages for each commit.
Related to #273
Close#288
> SquashFS | Fix some bugs
